name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        npm install -g grunt-cli
        npm install -g bower
    - name: build
      run: |
        npm install
        npm run compile
        npm run test
        grunt coveralls
